### ISSUE TITLE
linux编译不过

### ISSUE THREAD

**Issue by korialuo** [cloudwu/sharplua#1]
我的开发环境是linux-mint， lua版本5.3.4-rc3，gcc5.4，mono-mcs4.2.1.0， make all后，发现2处编译不过。
1. __declspec(dllexport)是win下才有吧？这里我用宏判断了，已解决。
2. 另外一处是link错误。错误信息如下：
gcc -g -Wall -o sharplua.dll --shared sharplua.c -I/usr/local/include -L/usr/local/lib -llua
/usr/bin/ld: /tmp/ccoCCYJA.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/tmp/ccoCCYJA.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:4: recipe for target 'sharplua.dll' failed
make: *** [sharplua.dll] Error 1

**Comment by cloudwu** [comment]
linux 自己搞定。加上 -fPIC

**Comment by korialuo** [comment]
加上-fPIC过后， 仍然有错误。 我是自己编译的lua， 直接make linux编译的。 错误信息：
gcc -g -Wall -o sharplua.dll --shared -fPIC sharplua.c -I/usr/local/include -L/usr/local/lib -llua
/usr/bin/ld: /usr/local/lib/liblua.a(lapi.o): relocation R_X86_64_32 against `luaO_nilobject_' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/liblua.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:4: recipe for target 'sharplua.dll' failed
make: *** [sharplua.dll] Error 1

**Comment by cloudwu** [comment]
出错信息已经写的很清楚了，建议翻墙用 google translate

**Comment by korialuo** [comment]
谢谢云风。 已经解决。
